name: E2E Tests
on:
  push:
    branches:
      - main  # Run tests on push to the main branch
  pull_request:  # Run tests for pull requests

jobs:
  test-e2e:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetch repository code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use a compatible Node.js version

      - name: Install dependencies
        run: npm ci  # Install dependencies based on package-lock.json

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps

      - name: Run Tests
        run: npx playwright test mytest/Tests/home.spec.ts

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with: 
          name: TestResultsForGithub
          path: test-resultsForGithub